video:
    resource: "@VideoBundle/Controller/"
    type:     annotation
    prefix:   /videos

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
